services:
  todo-flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    # volumes:
    #   # Uncomment the following line for development to enable live reload
    #   - .:/app
    restart: unless-stopped